# Generated by Django 5.2.9 on 2025-12-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='相册名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL 别名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='封面图')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='图片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.album', verbose_name='相册')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['album', 'order', '-created_at'],
            },
        ),
    ]
