# Generated by Django 5.2.9 on 2025-12-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_album_is_encrypted_album_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, help_text='用于检测密码是否被修改', null=True, verbose_name='密码更新时间'),
        ),
    ]
