# Generated by Django 5.2.9 on 2025-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_encrypted',
            field=models.BooleanField(default=False, verbose_name='是否加密'),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, help_text='加密文章的访问密码', max_length=128, verbose_name='访问密码'),
        ),
    ]
