# Generated by Django 5.2.9 on 2025-12-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='收件人')),
                ('subject', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('message', models.TextField(verbose_name='邮件内容')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('success', '发送成功'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('notification_type', models.CharField(blank=True, help_text='例如：comment_reply, new_comment, comment_approval', max_length=50, verbose_name='通知类型')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('related_object_type', models.CharField(blank=True, max_length=100, verbose_name='关联对象类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮件日志',
                'verbose_name_plural': '邮件日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='common_emai_status_a5dd3c_idx'), models.Index(fields=['recipient', 'created_at'], name='common_emai_recipie_b336c4_idx')],
            },
        ),
    ]
