# Generated by Django 5.2.9 on 2025-12-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='我的博客', max_length=100, verbose_name='博客名称')),
                ('site_description', models.TextField(blank=True, max_length=500, verbose_name='博客描述')),
                ('site_keywords', models.CharField(blank=True, max_length=200, verbose_name='关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
    ]
