# Generated by Django 5.2.9 on 2025-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='支持 PNG、JPG、SVG 等格式，建议尺寸 24x24 像素', null=True, upload_to='settings/', verbose_name='站点图标'),
        ),
    ]
