# Generated by Django 5.2.9 on 2025-12-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sitesettings_site_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('url', models.CharField(max_length=200, verbose_name='链接地址')),
                ('is_builtin', models.BooleanField(default=False, help_text='系统内置菜单不可删除', verbose_name='系统内置')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_content',
            field=models.TextField(blank=True, help_text='支持 Markdown 格式', verbose_name='关于页面内容'),
        ),
    ]
