# Generated by Django 5.2.9 on 2025-12-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_navigationitem_sitesettings_about_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='is_accessible',
            field=models.BooleanField(default=True, help_text='控制是否可以通过URL访问，设为False时访问会显示404', verbose_name='是否可访问'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='控制是否在导航栏显示', verbose_name='是否显示'),
        ),
    ]
