# Generated by Django 5.2.9 on 2025-12-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_navigationitem_is_accessible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_from',
            field=models.CharField(blank=True, help_text='显示的发件人邮箱地址', max_length=200, verbose_name='发件人邮箱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, help_text='例如：smtp.gmail.com', max_length=200, verbose_name='SMTP 服务器'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='邮箱密码或应用专用密码', max_length=200, verbose_name='SMTP 密码'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='发送邮件的邮箱地址', max_length=200, verbose_name='SMTP 用户名'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.IntegerField(default=587, help_text='常用端口：587 (TLS) 或 465 (SSL)', verbose_name='SMTP 端口'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='是否使用 SSL 加密', verbose_name='使用 SSL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='是否使用 TLS 加密', verbose_name='使用 TLS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_email_notification',
            field=models.BooleanField(default=False, help_text='是否启用邮件通知功能', verbose_name='启用邮件通知'),
        ),
    ]
