# Generated by Django 5.2.9 on 2025-12-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '私密')], default='public', max_length=10, verbose_name='可见性')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '瞬间',
                'verbose_name_plural': '瞬间',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MomentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_records', to='moments.moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '瞬间点赞',
                'verbose_name_plural': '瞬间点赞',
            },
        ),
        migrations.AddIndex(
            model_name='moment',
            index=models.Index(fields=['-published_at'], name='moments_mom_publish_bfd8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='moment',
            index=models.Index(fields=['author', '-published_at'], name='moments_mom_author__25c798_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='momentlike',
            unique_together={('moment', 'user')},
        ),
    ]
